class Constants:
    locationcolors = {"Architect's Ring": "#FBF578",
                      "The Wolfswood": "#578C4E",
                      "Pelias' Keep": "#C1B8A3",
                      "Blue": "#12339F",
                      "SKT": "#BEBEBE",
                      "Sanguine Halls": "#9F0100",
                      "PORTAL": "#DBE5E0",
                      "Ruin": "#3D6EA5",
                      "Quest Reward": "#C2A1C5",
                      "Transmogrifier": "#6834A5",
                      "Brown": "#6A340A",
                      "White": "#FCFCFC",
                      "Orange": "#FCA800",
                      "Magenta": "#FC54FC",
                      "Light Blue": "#49C0E2",
                      "Yellow": "#FCFC54",
                      "Lime": "#54FC54",
                      "Pink": "#FC68B2",
                      "Gray": "#545454",
                      "Light Gray": "#A8A8A8",
                      "Cyan": "#00A8A8",
                      "Purple": "#A800A8",
                      "Teal": "#46B4B3",
                      "Shifting": "#7DFCD1",
                      "Patron": "#80D817",
                      "Forum": "#7E7E00",
                      "TOV": "#C6A0C6",
                      "Docks": "#196281",
                      "Carnival": "#CE2D27",
                      "Delves": "#B26F27",
                      "Rush": "#C01E55",
                      "Horseman": "#8C3318",
                      "Mist": "#664B5A",
                      "Remorse": "#EBE3D3",
                      "Depths": "#5C2C85",
                      "Eldrask": "#85CCF7",
                      "Hekawt": "#FCB23D",
                      "Isles Delves": "#FFEDB8",
                      "Isles Casino": "#E0E2FF",
                      "Isles Overworld": "#E0EBFF",
                      "Celsian Isles": "#F4F8FF",
                      "Valley Delves": "#FFEDB8",
                      "Armory": "#FFEDB8",
                      "Valley Casino": "#FFFAEC",
                      "Valley Overworld": "#FFFFE8",
                      "King's Valley": "#F5FFF5",
                      "Lowtide Smuggler": "#CACAE7",
                      "Azacor": "#F6C5B6",
                      "Labs": "#B2AAC1",
                      "Willows": "#006300",
                      "Sanctum": "#51A800",
                      "Reverie": "#780E46",
                      "Corridors": "#890000",
                      "Verdant": "#158115",
                      "Kaul": "#9ED292"}

    classcolors = {"Alchemist": "#5ea819",
                   "Warrior": "#db2445",
                   "Cleric": "#fcc443",
                   "Rogue": "#35383c",
                   "Mage": "#a11ecc",
                   "Scout": "#2488c6",
                   "Warlock": "#c524b7",
                   "Generalist": "#9d8d8f"}

    infotext = "#545454"

    masterworkstar = "#fcb23d"

    charmstatcolors = {"negativeCharm": "#ce2d27",
                       "positiveCharm": "#49c0e2"}

    tiercolors = {"tier 5": "#545454",
                  "tier 4": "#545454",
                  "tier 3": "#545454",
                  "tier 2": "#545454",
                  "tier 1": "#545454",
                  "uncommon": "#bebebe",
                  "unique": "#c6a0c6",
                  "rare": "#49c0e2",
                  "artifact": "#ce2d27",
                  "epic": "#b114e0",
                  "legendary": "#fcd400",
                  "base": "#fcf774",
                  "patron": "#80D817"}

    statformats = {("adrenaline", "soul_speed"): "ENCHANT",
                   ("speed_flat", "speed_percent"): "ATTRIBUTE",
                   "crippling": "CURSE",
                   ("ice_aspect_m", "fire_aspect_m", "thunder_aspect_m", "sweeping_edge", "knockback", "quake", "smite",
                    "duelist", "chaotic", "hex_eater", "decay", "bleeding", "wind_aspect_m", "earth_aspect_m",
                    "stamina", "first_strike"): "ENCHANT",
                   ("second_wind", "inferno", "regicide", "aptitude", "triage", "trivium"): "ENCHANT",
                   ("intuition", "weightless", "radiant", "darksight", "void_tether", "resurrection"): "SINGLE_ENCHANT",
                   ("projectile_prot", "blast_prot", "fire_prot", "melee_prot", "magic_prot", "feather_falling"):
                   "ENCHANT",
                   ("knockback_resistance_flat", "attack_damage_percent", "attack_speed_flat", "attack_speed_percent",
                    "magic_damage_percent", "projectile_damage_percent", "projectile_speed_percent", "thorns_flat",
                    "thorns_percent", "throw_rate_percent"): "ATTRIBUTE",
                   ("regen", "life_drain", "sustenance"): "ENCHANT",
                   ("max_health_flat", "max_health_percent"): "ATTRIBUTE",
                   "anemia": "CURSE",
                   ("efficiency", "eruption", "sapper", "multitool", "fortune", "lure"): "ENCHANT",
                   ("silk_touch", "infinity_tool", "jungle_s_nourishment", "excavator"): "SINGLE_ENCHANT",
                   ("arcane_thrust", "worldly_protection"): "ENCHANT",
                   ("ashes_of_eternity", "rage_of_the_keter"): "SINGLE_ENCHANT",
                   ("quick_charge", "point_blank", "sniper", "multishot", "piercing", "retrieval", "punch",
                    "ice_aspect_p", "fire_aspect_p", "thunder_aspect_p", "recoil", "explosive",
                    "multiload"): "ENCHANT",
                   "infinity_bow": "SINGLE_ENCHANT",
                   ("shielding", "poise", "inure", "steadfast", "ethereal", "reflexes", "evasion", "tempo",
                    "cloaked", "guard"): "ENCHANT",
                   "adaptability": "SINGLE_ENCHANT",
                   ("ineptitude", "shrapnel", "vanishing", "projectile_fragility", "melee_fragility",
                    "magic_fragility", "blast fragility", "fire_fragility"): "CURSE",
                   ("two_handed", "corruption", "irreparability"): "SINGLE_CURSE",
                   ("depth_strider", "abyssal", "respiration", "riptide"): "ENCHANT",
                   ("gills", "aqua_affinity"): "SINGLE_ENCHANT",
                   "unbreaking": "ENCHANT",
                   ("unbreakable", "mending"): "SINGLE_ENCHANT",
                   "armor": "ATTRIBUTE",
                   "agility": "ATTRIBUTE",
                   "spell_power_base": "ATTRIBUTE",
                   ("attack_damage_base", "attack_speed_base", "projectile_damage_base", "projectile_speed_base",
                    "throw_rate_base"): "BASE_STAT"}

    statcolors = {"negativeStat": "#fc5454",
                  "positiveStat": "#5454fc",
                  "positiveDefence": "#32cafc",
                  "baseStat": "#00a800",
                  "enchant": "#bebebe"}

    gearorder = {"0": "Helmet",
                 "1": "Chestplate",
                 "2": "Leggings",
                 "3": "Boots",
                 "4": ("Mainhand", "Sword <M>", "Wand", "Axe", "Scythe", "Bow", "Crossbow", "Throwable", "Trident"),
                 "5": ("Offhand", "Offhand Shield", "Offhand Sword")}

    situationals = {0: "Shielding",
                    1: "Poise",
                    2: "Inure",
                    3: "Steadfast",
                    4: "Guard",
                    5: "SecondWind",
                    6: "Ethereal",
                    7: "Reflexes",
                    8: "Evasion",
                    9: "Tempo",
                    10: "Cloaked",
                    11: "Scout",
                    12: "ClericBlessing",
                    13: "FOL"}
